Controllers/MapController.cs
using Microsoft.AspNetCore.Mvc;
using PrestoTraxSite.Models;
using PrestoTraxSite.Services.Business;
using PrestoTraxSite.Services.Data;

namespace PrestoTraxSite.Controllers
{
    public class MapController : Controller
    {
        private readonly RecordDataService _recordService;
        private readonly DeviceDataService _deviceService;
        private readonly DeviceLogic _deviceLogic;
        public MapController()
        {
            _recordService = new();
            _deviceLogic = new();
            _deviceService = new();
        }
        
        //public IActionResult Index()
        //{
        //    return View();
        //}
        
        public async Task<IActionResult> Index()
        {
            List<DeviceModel> userDevices = await GetDevicesAsync();
            //Console.WriteLine($"{location.Longitude}, {location.Latitude}");
            return View(userDevices);
        }
        
        [HttpGet]
        [Route("/Map/GetDevicesAsync")]
        public async Task<List<DeviceModel>> GetDevicesAsync()
        {
            List<DeviceModel> userDevices = await _deviceService.GetUserDeviceInfo((int)HttpContext.Session.GetInt32("UUID"));
            foreach(DeviceModel userDevice in userDevices)
            {
                Console.WriteLine(userDevice.DeviceId);
            }
            await _deviceLogic.PopulateRecords(userDevices);
            return userDevices;
        }

        public async Task<IActionResult> GetMapComponent()
        {
            List<DeviceModel> userDevices = await GetDevicesAsync();
            //if (userRecords.Count == 0)
            //{
            //    throw new Exception("No records found");

            return PartialView("_MapComponent", userDevices);
        }

    }
}

Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using PrestoTraxSite.Models.API_Results;
using PrestoTraxSite.Models.Responses;
using PrestoTraxSite.Services.Data;

namespace PrestoTraxSite.Controllers
{
    public class UserController : Controller
    {
        private readonly UserDataService _dataService;
        public UserController()
        {
            _dataService = new();
        }
        public IActionResult Login()
        {
            return View();
        }

        public IActionResult Register()
        {
            return View();
        }

        public async Task<IActionResult> Authenticate()
        {
            ResultModel result = await _dataService.AuthenticateUser(Request.Form["username"], Request.Form["password"]);
            if(result.GetType() == typeof(ErrorResultModel))
            {
                ViewData["username"] = Request.Form["username"];
                ViewData["password"] = Request.Form["password"];
                return View("Login", result);
            }
            else
            {
                HttpContext.Session.SetInt32("UUID", ((UserResultModel)result).Uuid);
                return RedirectToAction("Index", "Home");
            }
        }

        public IActionResult Logout()
        {
            HttpContext.Session.Clear();
            return RedirectToAction("Index", "Home");
        }

        public async Task<IActionResult> RegisterUser()
        {
            if (Request.Form["password"] != Request.Form["confirmPassword"])
            {
                return View("Register", new ErrorResultModel("","Passwords do not match"));
            }
            ResultModel result = await _dataService.RegisterUser(Request.Form["email"], Request.Form["username"], Request.Form["password"]);
            if (result.GetType() == typeof(ErrorResultModel))
            {
                ViewData["email"] = Request.Form["email"];
                ViewData["username"] = Request.Form["username"];
                ViewData["password"] = Request.Form["password"];
                return View("Register", result);
            }
            else
            {
                HttpContext.Session.SetInt32("UUID", ((UserResultModel)result).Uuid);
                return RedirectToAction("Index", "Home");
            }
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PrestoTraxSite</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PrestoTraxSite.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PrestoTraxSite</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        @if (Context.Session.GetInt32("UUID") != null)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Map" asp-action="Index">Map</a>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="#" asp-action="#">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="#" asp-action="#">Contact</a>
                        </li>
                        @if (Context.Session.GetInt32("UUID") == null)
                        {
                            <li class="nav-item ms-auto">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Login">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Register">Register</a>
                            </li>
                        }
                        @if (Context.Session.GetInt32("UUID") != null)
                        {
                            <li class="nav-item ms-auto">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Logout">Logout</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - PrestoTraxSite - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_LoginForm.cshtml
@model ResultModel

<html>
    <head>
        <link rel="stylesheet" href="~/css/UserForm.css" />
    </head>
    <body>
        <p class="space">
                <h1 style="text-align: center">Login</h1>
        </p>
        <form asp-action="Authenticate" asp-controller="User" method="post" class="center-text">
            @{if (@Model != null && @Model.GetType() == typeof(ErrorResultModel))
                {
                    <div class="alert alert-danger formInput" role="alert">
                        @(((ErrorResultModel)Model).Message)
                    </div>
                }
            }
            
            <div class="form-group small-space">
                <label for="UserName" class="form-text">Username: </label>
                <input type="text" name="UserName" id="UserName" class="form-control formInput" placeholder="Username" value=@ViewData["username"] required/>
            </div>
            <div class="form-group small-space">
                <label for="Password" class="form-text">Password: </label>
                <input type="password" name="Password" id="Password" class="form-control formInput" placeholder="password" value=@ViewData["password"] required/>
            </div>
            <input type="submit" class="btn btn-primary small-space" value="Login"/>
        </form>
    </body>
</html>

Views/Shared/_MapComponent.cshtml
@model List<DeviceModel>

<html>
    <head>
        <script src='https://api.mapbox.com/mapbox-gl-js/v2.6.1/mapbox-gl.js'></script>
        <link href='https://api.mapbox.com/mapbox-gl-js/v2.6.1/mapbox-gl.css' rel='stylesheet' />
    <style>
        #LocationTable {
            position: relative;
            max-width: 80%;
            max-height: 20%;
            overflow-x: auto;
            overflow-y: auto;
            text-align: center;
            display: block;
        }
        #recentLocations {
            display:inline-block; float: right;
        }
        table, th, td{
            border: 1px solid black;
        }
    </style>
    </head>
    <body>

            <table id="LocationTable">
                <tr>
                    <th></th>
                    @for (int i = 0; i < Model.Count; i++)
                    {
                        <th>Device @(i + 1)</th>
                    }
                </tr>
                <tbody>
                    <tr>
                        <td>Latitude: </td>
                        @for(int i = 0; i < Model.Count; i++)
                        {
                            <td>@Model[i].DeviceLatitude</td>
                        }
                    </tr>
                    <tr>
                        <td>Longitude: </td>
                        @for(int i = 0; i < Model.Count; i++)
                        {
                            <td>@Model[i].DeviceLongitude</td>
                        }
                    </tr>
                    <tr>
                        <td>Moving: </td>
                        @for(int i = 0; i < Model.Count; i++)
                        {
                            <td>@Model[i].Moving</td>
                        }
                    </tr>
                </tbody>
            </table>
        <script>
            
        </script>
    </body>
    
</html>

Views/Shared/_RegisterForm.cshtml
@model ResultModel

<html>
    <head>
        <link rel="stylesheet" href="~/css/UserForm.css" />
    </head>
    <body>
        <p class="space">
                <h1 style="text-align: center">Register</h1>
        </p>
        <form asp-action="RegisterUser" asp-controller="User" method="post" class="center-text">
            @{if (@Model != null && @Model.GetType() == typeof(ErrorResultModel))
                {
                    <div class="alert alert-danger formInput" role="alert">
                        @(((ErrorResultModel)Model).Message)
                </div>
            }
        }
        <div class="form-group small-space">
                <label for="Email" class="form-text">E-mail Address: </label>
                <input type="text" name="Email" id="Email" class="form-control formInput" placeholder="E-mail Address" value=@ViewData["email"] required/>
            </div>
            <div class="form-group small-space">
                <label for="UserName" class="form-text">Username: </label>
                <input type="text" name="UserName" id="UserName" class="form-control formInput" placeholder="Username" value=@ViewData["Username"] required/>
            </div>
            <div class="form-group small-space">
                <label for="Password" class="form-text">Password: </label>
                <input type="password" name="Password" id="Password" class="form-control formInput" placeholder="Password" value=@ViewData["Password"] required/>
            </div>
            <div class="form-group small-space">
                <label for="ConfirmPassword" class="form-text">Confirm Password: </label>
                <input type="password" name="ConfirmPassword" id="ConfirmPassword" class="form-control formInput" placeholder="Confirm Password" required/>
            </div>
            <input type="submit" class="btn btn-primary small-space" value="Register"/>
        </form>
    </body>
</html>